import { VeyaClient }        from './client';
import { InvoicesResource }  from './resources/invoices';
import { CustomersResource } from './resources/customers';
import { WebhooksResource }  from './resources/webhooks';
import { VeyaConfig }        from './types';
import { VeyaError }         from './errors';

// ─────────────────────────────────────────────────────────────
// Re-export everything a merchant needs
// They should never need to import from internal files
// ─────────────────────────────────────────────────────────────

export * from './types';
export * from './errors';
export { InvoicesResource }  from './resources/invoices';
export { CustomersResource } from './resources/customers';
export { WebhooksResource }  from './resources/webhooks';

// ─────────────────────────────────────────────────────────────
// Minimum secret length constant (exported for merchant testing)
// ─────────────────────────────────────────────────────────────

const MIN_WEBHOOK_SECRET_LENGTH = 32;

// ─────────────────────────────────────────────────────────────
// Main SDK Class
// ─────────────────────────────────────────────────────────────

export class Veya {
  private readonly client:   VeyaClient;
  private _webhooks?:        WebhooksResource;

  /** Invoice operations: create, retrieve, list, cancel */
  readonly invoices:  InvoicesResource;

  /** Customer operations: create, retrieve, list */
  readonly customers: CustomersResource;

  /**
   * Whether this SDK instance is running in test mode.
   * True when the API key starts with vk_test_
   * No real payments are processed in test mode.
   */
  readonly isTestMode: boolean;

  constructor(config: VeyaConfig) {

    // ── Validate API Key Presence ──────────────────────────────────────
    if (!config.apiKey) {
      throw new VeyaError(
        'API key is required. ' +
        'Get yours from the Veya merchant dashboard under Settings → API Keys. ' +
        'Load it from an environment variable: process.env.VEYA_API_KEY',
        400,
        'missing_api_key'
      );
    }

    // ── Validate API Key Format ────────────────────────────────────────
    //
    // All Veya API keys start with "vk_".
    // This catches common mistakes like passing a webhook secret,
    // a JWT token, or a key from a different service.

    if (!config.apiKey.startsWith('vk_')) {
      throw new VeyaError(
        `Invalid API key format. ` +
        `Veya API keys start with "vk_test_" or "vk_live_". ` +
        `Received a key starting with "${config.apiKey.slice(0, 6)}...". ` +
        `Check that you are using the correct key from the Veya dashboard.`,
        400,
        'invalid_api_key_format'
      );
    }

    // ── Detect Test vs Live Mode ───────────────────────────────────────
    this.isTestMode = config.apiKey.startsWith('vk_test_');

    if (this.isTestMode) {
      console.warn(
        '[Veya SDK] ⚠️  TEST MODE ACTIVE\n' +
        '            No real payments will be processed.\n' +
        '            Switch to a live key (vk_live_...) before going to production.'
      );
    }

    // ── Validate Webhook Secret (if provided) ──────────────────────────
    //
    // We validate the secret here at construction time so the merchant
    // gets a clear error immediately, not buried inside a webhook handler
    // when their first real payment arrives.

    if (config.webhookSecret !== undefined) {
      if (
        !config.webhookSecret ||
        config.webhookSecret.trim().length < MIN_WEBHOOK_SECRET_LENGTH
      ) {
        throw new VeyaError(
          `webhookSecret must be at least ${MIN_WEBHOOK_SECRET_LENGTH} characters long. ` +
          `Use the secret generated by the Veya dashboard, not a custom string. ` +
          `Short or weak secrets can be brute-forced, allowing attackers to ` +
          `forge fake payment notifications.`,
          400,
          'invalid_webhook_secret'
        );
      }
    }

    // ── Initialize HTTP Client ─────────────────────────────────────────
    this.client = new VeyaClient(config);

    // ── Initialize Resources ───────────────────────────────────────────
    this.invoices  = new InvoicesResource(this.client);
    this.customers = new CustomersResource(this.client);

    // ── Initialize Webhooks (only if secret was provided) ──────────────
    if (config.webhookSecret) {
      this._webhooks = new WebhooksResource(config.webhookSecret);
    }
  }

  /**
   * Webhook verification resource.
   *
   * Requires webhookSecret to be set in your Veya config at initialization.
   * Throws a clear error if the secret was not provided, rather than
   * crashing with a null reference when your first webhook arrives.
   *
   * @throws {VeyaError} - If webhookSecret was not provided at initialization
   *
   * @example
   * const veya = new Veya({
   *   apiKey:        process.env.VEYA_API_KEY!,
   *   webhookSecret: process.env.VEYA_WEBHOOK_SECRET!
   * });
   *
   * const event = veya.webhooks.verify(payload, signature);
   */
  get webhooks(): WebhooksResource {
    if (!this._webhooks) {
      throw new VeyaError(
        'Webhook verification requires a webhookSecret. ' +
        'Initialize the SDK with: new Veya({ apiKey: "...", webhookSecret: "..." })',
        400,
        'missing_webhook_secret'
      );
    }
    return this._webhooks;
  }
}

export default Veya;
